### ISSUE TITLE
trapz deprecated in scipy 1.14.1 breaks MW calculation

### ISSUE THREAD

**Issue by antoniocalio95** [jbhopkins/bioxtasraw#10]
I updated scipy for a different reason today, and it broke the MW calculation in RAW. 
Apparently, scipy.integrate.trapz has been deprecated in favour of scipy.integrate.trapezoid.

Here's the complete error report:

`An unexpected error has occurred, please report it to the developers.
System: Windows-11-10.0.22631-SP0
RAW version: 2.3.0
Prebuilt: False
ATSAS version: 3.2.1

Error:
Traceback (most recent call last):

  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\bioxtasraw\RAW.py", line 9573, in _onPopupMenuChoice
    Mainframe.showMolWeightFrame(sasm, selectedSASMList[0])

  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\bioxtasraw\RAW.py", line 1107, in showMolWeightFrame
    molweightframe = RAWAnalysis.MolWeightFrame(self, 'Molecular Weight',
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\bioxtasraw\RAWAnalysis.py", line 1768, in __init__
    self._initSettings()

  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\bioxtasraw\RAWAnalysis.py", line 1945, in _initSettings
    wx.FindWindowById(self.ids['VC']['sup_plot'], self).plotSASM(self.sasm, vc_qmax)

  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\bioxtasraw\RAWAnalysis.py", line 3898, in plotSASM
    q, intI = self._calcInt(sasm, qmax)
              ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\bioxtasraw\RAWAnalysis.py", line 3892, in _calcInt
    y[a-1] = integrate.trapz(qi[:a],q[:a])
             ^^^^^^^^^^^^^^^

AttributeError: module 'scipy.integrate' has no attribute 'trapz'
`

**Comment by antoniocalio95** [comment]
Just realized that this has already been fixed, sorry!
I did update RAW too today (after updating scipy and other things), but for some reason I must have gotten and older version, even though it did say it was 2.3.0 (as you can see from the traceback above). Sorry again for opening a useless issue!

**Comment by jbhopkins** [comment]
So I can shed a bit of light on the version confusion. The released version 2.3.0 does indeed have this issue. I fixed it in August, and it is fixed in the latest version of RAW available from the git, but not yet in any releases. The version number has not been udpated in the git yet, so it's still 2.3.0, hence why you're seeing two version 2.3.0, one with the problem (the code released as 2.3.0) and one without (the code from the git).
